### PR TITLE
Fix example code

### PR DESCRIPTION
**Pull request by shge**
* Fix example code as it was not working
* Small changes on README

### CODE REVIEW

**Comment by yu-san-19** [comment]
@shge 
Thanks for PR! ✨ 
This will be reviewed by @jscg/borscht-moderators and be merged soon.

**Comment by yu-san-19** [comment]
@1010mark 
cc/ @jscg/borscht-moderators 

I'm going to merge this, but we should think about this example code:
```py
cg = ChainGenerator.ChainGenerator(text) # Generate instance of class that generate chains
cg.dump() # Dump json file written about chains' info.
tg = TextGenerator.TextGenerator("chain.json") # Generate instance of class that generate sentence
```

I think `ChainGenerator.ChainGenerator` or `TextGenerator.TextGenerator` is NOT clean.
I think we should change it `<pypi_pkg_name>.ChainGenerator`, `<pypi_pkg_name>.TextGenerator`.
What do you think about this?

**Comment by yu-san-19** [comment]
@1010mark 
For now, I want to merge it.

**Review by yum45f — DISMISSED** [review]
LGTM!! 👍 🎉

**Comment by shge** [comment]
@yu-san-19 
>I think ChainGenerator.ChainGenerator or TextGenerator.TextGenerator is NOT clean.
I think we should change it <pypi_pkg_name>.ChainGenerator, <pypi_pkg_name>.TextGenerator.
What do you think about this?

I fixed `__init__.py`. Thanks!

**Review by yum45f — APPROVED** [review]
Thank you for the fix!
That's all OK, I'm just merging now 🚀 
Thanks!

**Pull request merged**
